export enum USER_ACTIONS_TYPES {
    SIGN_IN = "SIGN_IN",
    SIGN_OUT = "SIGN_OUT",

}

export enum MESSAGE_ACTIONS_TYPES {
    SUCCESS = "SUCCESS",
    ERROR = "ERROR",
    CLEAR = "CLEAR"
}

export enum COURSE_ACTIONS_TYPES {
    SUBSCRIBE_COURSE = 'SUBSCRIBE_COURSE',
    UNSUBSCRIBE_COURSE="UNSUBSCRIBE_COURSE",
    CREATE_COURSE ="CREATE_COURSE",
    EDIT_COURSE="EDIT_COURSE",
    FETCH_COURSE = "FETCH_COURSE",
    FETCH_COURSES ="FETCH_COURSES"
}


export const CREATE_REVIEW = "CREATE_REVIEW";
export const EDIT_REVIEW = "EDIT_REVIEW";
export const FETCH_REVIEW = "FETCH_REVIEW";

export const CHECK_NEWSTUDENT = "CHECK_NEWSTUDENT";

export const FETCH_SHOPCART = "FETCH_SHOPCART";
export const ADD_SHOPCART = "ADD_TO_SHOPCART";
export const DELETE_SHOPCART = "DELETE_SHOPCART";

//export const DELTE_REVIEW = "DELTE_REVIEW"
